### ISSUE TITLE
data.replaceAll is not a function

### ISSUE THREAD

**Issue by HouDiZhong** [donnikitos/vite-plugin-html-inject#1]
const replaceAttrMatcher = new RegExp("{=[$]([a-z0-9_-]+)}", "gi") 
data = data.replaceAll(replaceAttrMatcher）
Regular is already a global mode,No need to use replaceAll，And replaceAll support is not good

**Comment by donnikitos** [comment]
Seems like that happens with NodeJS before version 15, due to not implemented `.replaceAll()` function.
Will use `.replace()` for broader support.
