### ISSUE TITLE
Question: is there a way to load an HTML snippet conditionally?

### ISSUE THREAD

**Issue by anthonygore** [donnikitos/vite-plugin-html-inject#12]
I'm wondering if there's a way to load a snippet based on an env variable for example.

**Comment by donnikitos** [comment]
That's not build in, but I assume you could use **HTML Env Replacements**:
https://vitejs.dev/guide/env-and-mode#html-env-replacement

**Comment by donnikitos** [comment]
Another pretty convenient way is to use EJS templating: https://www.npmjs.com/package/vite-plugin-ejs
