### ISSUE TITLE
Vite 5 throws several warnings about deprecations

### ISSUE THREAD

**Issue by limonte** [donnikitos/vite-plugin-html-inject#6]
Hello and thank you for your plugin 🙌 

I've updated Vite to v5 and now it's throwing these warnings and all of them seem to be related to `vite-plugin-html-inject`:

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
plugin 'static-html-loader' uses deprecated 'enforce' option. Use 'order' option instead.
plugin 'static-html-loader' uses deprecated 'transform' option. Use 'handler' option instead.
```

**Comment by donnikitos** [comment]
Hi, thanks for the heads-up.
Will review the changes and deprecations in Vite 5 and implement them into the plugin.

May the code be with you!

**Comment by IGx89** [comment]
@donnikitos would you like help with that? I could submit a PR if so. I already have another PR open to address a typing issue (#7).

**Comment by donnikitos** [comment]
@limonte, @IGx89 Fixes are on the way and will be most likely published tomorrow :)

**Comment by limonte** [comment]
@donnikitos thank you for addressing this issue! I can confirm that warnings are gone 🙌
