### ISSUE TITLE
Vite 5 fails to build because of the syntax

### ISSUE THREAD

**Issue by eye-wave** [donnikitos/vite-plugin-html-inject#8]
```
ERROR  [vite:build-html] Unable to parse HTML; parse5 error code unexpected-equals-sign-before-attribute-name
34 |    <body>
35 |      <main id="app">
36 |        <load ="" />
   |              ^
37 |      </main>
38 |
```

**Comment by eye-wave** [comment]
i don't understand the syntax choice. This could have been easily avoided like this:

```html
<load src="html/component.html" />
```

**Comment by donnikitos** [comment]
Initially it was chosen to distinguish the tag from regular HTML. In the aftermath however, I agree, it should be `<load src="html/component.html" />` and will be updated in the future: See issue #5.
